#!/usr/bin/env bash
# Execute a command in the container
set -ue
thisdir="$(dirname "${BASH_SOURCE[0]}")"
echo "thisdir=$thisdir"
source "${thisdir}/common"


if [ "${1-}" = "--help" ]; then 
echo <<EOF
Usage: cexec command [args...]

Execute `command` in the container. This script starts the Singularity
container and executes the given command therein. The project root is mapped 
to the folder `/proj` inside the container.

EOF
exit 0
fi

# Basic test whether the current directory is the project dir
# should have a script named "cexec" that calls this script
if [ ! -f "cexec" ]; then
  echo "Error: Please call this script from your project directory" >&2
  exit 1
fi

singularity exec \
  "${ARGS_INSTANCE[@]}" \
  "${ARGS_EXEC[@]}" \
  "$CONTAINER" \
  "$@"


